services: 
  web: 
    container_name: estadao_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - estadao_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'


networks:
  estadao_network:
    driver: bridge
